# Generated by Django 2.1.7 on 2019-03-23 02:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='produto',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=30),
        ),
    ]
